name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Ensure we're using the latest version

    - name: Set up Python
      uses: actions/setup-python@v5  # Ensure we're using the latest version
      with:
        python-version: '3.x'
    
    - name: Verify Python Version
      run: python --version  # Verify that Python is installed correctly
    
    - name: Upgrade Pip
      run: python -m pip install --upgrade pip  # Upgrade pip to the latest version
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Install dependencies from requirements.txt
    
    - name: Verify Pytest Installation
      run: pytest --version  # Verify that pytest is installed correctly
    
    - name: Run tests
      run: pytest  # Run the tests using pytest



