name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Upgrade Pip
      run: python -m pip install --upgrade pip
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install flake8 black mypy
    
    - name: Verify Python Version
      run: python --version
    
    - name: Lint code with flake8
      run: flake8 .
    
    - name: Format code with black
      run: black --check .
    
    - name: Type check with mypy
      run: mypy .
